---
title: "Discrete time survival analysis - transitions from smoking to e-cigarette use/non-use in ALSPAC"
author: "Alexandria Andrayas"
date: "05/02/2024"
output: 
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = TRUE, message = FALSE)
```

```{r load-packages}
library(haven)
library(labelled)
library(sticky)
library(survey)
library(dplyr)
library(ggpubr)
library(mice)
library(mitools)
library(gt)
library(gtsummary)
library(discSurv)
```

# Load data and define labels

```{r data-labs}
# set up data
subdf <- read_dta('//rdsfcifs.acrc.bris.ac.uk/MRC-IEU-research/projects/ieu2/p7/025/working/data/vaping_sub_measures.dta')
subdf <- to_factor(subdf, sort_levels='auto')
subdf <- data.frame(subdf)
subdf <- sticky_all(subdf)

subdf$id <- 1:nrow(subdf)

load('//rdsfcifs.acrc.bris.ac.uk/MRC-IEU-research/projects/ieu2/p7/025/working/data/vaping_impdfs.rda')
impdfs <- lapply(impdfs, function(x){
  x[,'id'] <- 1:nrow(x)
  return(x)
})

# 4 baseline exposures
baseline_exp <- c('sex', 'ethnicity', 'hhincome_11', 'parent_dailsmk_12')

# 11 main exposures
main_exp <- c('bmi_18_gr', 'exerc_18', 'qual_20', 'bingalc_20', 'cana_20', 'drug_20', 'friends_smk_20', 'mfq_21_gr', 'townsend_21_gr', 'parent_21', 'freqsmk_21')

# 5 timepoints
vaps <- c('vap22', 'vap23', 'vap24', 'vap28', 'vap30')

# 4 outcomes
outcomes <- c('nonuse', 'ecig', 'exclecig', 'dual')
outcomes_labs <- c('Non-use', 'Any e-cig use', 'Exclusive e-cig use', 'Dual use')

# table labels
tab_labs <- c('Sex assigned at birth', 'Ethnicity', 'Average household income, GBP per week (11y)', 'Parental smoking (12y)', 'BMI (18y)', 'Frequency of exercise, past year (18y)', 'Educational qualifications (20y)', 'Binge drinking, six or more units (20y)','Cannabis use (20y)', 'Drug use (20y)','Peer smoking (20y)','Mood and Feelings Questionnaire scores (21y)','G1 Townsend deprivation score, quintiles (21y)','Is a parent (21y)','Smoking frequency (21y)')

# change discrete time-to-event data to (1 = 22y, 2 = 23y, 3 = 24y, 4 = 28y, 5 = 30y)
changetimeto <- function(df){
  df$timeto[df$timeto %in% 7] <- 4
  df$timeto[df$timeto %in% 9] <- 5
  return(df)
}
subdf <- changetimeto(subdf)
impdfs <- lapply(impdfs, changetimeto)
rm(changetimeto)

#168 complete cases for exposures and outcomes
subdf$completecase <- ifelse(apply(subdf[,c('firstevent','timeto',baseline_exp,main_exp)],1,anyNA)==F,1,0)
table(subdf$completecase)
subdf_cc <- subdf[subdf$completecase %in% 1,]

# head data
head(subdf[,c('firstevent', 'timeto', outcomes, vaps, baseline_exp)], 20)
head(impdfs[[1]][,c('firstevent', 'timeto', outcomes, vaps, baseline_exp)], 20)
```

# Reshape data to person-period format

```{r reshape-data}
dataLongit <- function(df){
  out <- list()
  for(i in outcomes){
    out[[i]] <- dataLong(dataShort = df, timeColumn = "timeto", eventColumn = i)
  }
  return(out)
}
subdfLong <- dataLongit(subdf_cc)
impdfsLong <- lapply(impdfs, dataLongit)
rm(dataLongit)
```

# Specify survey designs

```{r svy-designs}
svydes_cc <- lapply(subdfLong, function(x) svydesign(id = ~1, weights = ~weights, data = x))
svydes_imp <- lapply(impdfsLong, function(data) lapply(data, function(x) svydesign(id = ~1, weights = ~weights, data = x)))
```

# Fit baseline Gompertz Models

Using this tutorial: https://www.rensvandeschoot.com/tutorials/discrete-time-survival/

```{r baseline-gompertz-mod, warnings=F}
baseline_mods <- list('cc' = lapply(outcomes, function(x) glm(formula = y ~ timeInt, family = binomial(link = "cloglog"), data = subdfLong[[x]])),
                      'cc_w' = lapply(outcomes, function(x) svyglm(formula = y ~ timeInt, family = binomial(link = "cloglog"), data = subdfLong[[x]], design=svydes_cc[[x]])),
                      'imp' = lapply(1:100, function(x) lapply(outcomes, function(data) glm(formula = y ~ timeInt, family = binomial(link = "cloglog"), data = impdfsLong[[x]][[data]]))),
                      'imp_w' = lapply(1:100, function(x) lapply(outcomes, function(data) svyglm(formula = y ~ timeInt, family = binomial(link = "cloglog"), data = impdfsLong[[x]][[data]], design=svydes_imp[[x]][[data]])))
)
#Warning: non-integer #successes in a binomial glm!

nameit <- function(df){
  setNames(df, outcomes)
  return(df)
}
baseline_mods$cc <- nameit(baseline_mods$cc)
baseline_mods$cc_w <- nameit(baseline_mods$cc_w)
baseline_mods$imp <- lapply(baseline_mods$imp, nameit)
baseline_mods$imp_w <- lapply(baseline_mods$imp_w, nameit)
```

# Get model equations for full models

```{r specify-models}
alist <- list(
    cc = setNames(vector(mode='list', length=length(outcomes)),outcomes),
    cc_w = setNames(vector(mode='list', length=length(outcomes)),outcomes),
    imp = setNames(vector(mode='list', length=length(outcomes)),outcomes),
    imp_w = setNames(vector(mode='list', length=length(outcomes)),outcomes)
  )

getmodeqs <- function(x){
  out <- list(
    'baseline' = 
      paste0('y ~ timeInt + ', paste0(baseline_exp, collapse = ' + ')),
    'bmi_18_gr' = 
      paste0('y ~ timeInt + ', paste0(c(baseline_exp,'bmi_18_gr'), collapse = ' + ')),
    'exerc_18' = 
      paste0('y ~ timeInt + ', paste0(c(baseline_exp,'exerc_18'), collapse = ' + ')),
    'qual_20' = 
      paste0('y ~ timeInt + ', paste0(c(baseline_exp,'qual_20'), collapse = ' + ')),
    'bingalc_20' = 
      paste0('y ~ timeInt + ', paste0(c(baseline_exp,'bingalc_20'), collapse = ' + ')),
    'cana_20' = 
      paste0('y ~ timeInt + ', paste0(c(baseline_exp,'cana_20'), collapse = ' + ')),
    'drug_20' = 
      paste0('y ~ timeInt + ', paste0(c(baseline_exp,'drug_20'), collapse = ' + ')),
    'friends_smk_20' = 
      paste0('y ~ timeInt + ', paste0(c(baseline_exp, 'friends_smk_20'), collapse = ' + ')),
    'mfq_21_gr' = 
      paste0('y ~ timeInt + ', paste0(c(baseline_exp,'mfq_21_gr'), collapse = ' + ')),
    'townsend_21_gr' = 
      paste0('y ~ timeInt + ', paste0(c(baseline_exp,'townsend_21_gr'), collapse = ' + ')),
    'parent_21' = 
      paste0('y ~ timeInt + ', paste0(c(baseline_exp,'parent_21'), collapse = ' + ')),
    'freqsmk_21' = 
      paste0('y ~ timeInt + ', paste0(c(baseline_exp,'freqsmk_21'), collapse = ' + '))
  )
  return(out)
}
modeqs <- setNames(lapply(outcomes, getmodeqs), outcomes)
rm(getmodeqs)
```

# Fit full models

```{r full-gompertz-mod, warning=FALSE}
fitmodels <- function(modeqs){
  models <- alist
  for(i in c('cc','cc_w','imp','imp_w')){
    for(j in outcomes){
      if(i %in% 'cc'){
        models[[i]][[j]] <- lapply(modeqs[[j]], function(x) glm(formula=formula(x), family=binomial(link = "cloglog"), data=subdfLong[[j]]))
        } else if(i %in% 'cc_w'){
          models[[i]][[j]] <- lapply(modeqs[[j]], function(x) svyglm(formula=formula(x), family=binomial(link = "cloglog"), data=subdfLong[[j]], design=svydes_cc[[j]]))
        } else if(i %in% 'imp'){
          mods <- list()
          for(k in 1:100){mods[[k]] <- lapply(modeqs[[j]], function(x) glm(formula=formula(x), family=binomial(link = "cloglog"), data = impdfsLong[[k]][[j]]))}
          models[[i]][[j]] <- setNames(lapply(c('baseline',main_exp), function(x) lapply(mods, '[[', x)),c('baseline',main_exp))
          models[[i]][[j]] <- lapply(models[[i]][[j]], as.mira)
        } else if(i %in% 'imp_w'){          
          mods <- list()
          for(k in 1:100){mods[[k]] <- lapply(modeqs[[j]], function(x) svyglm(formula=formula(x), family=binomial(link = "cloglog"), data = impdfsLong[[k]][[j]], design=svydes_imp[[k]][[j]]))}
          models[[i]][[j]] <- setNames(lapply(c('baseline',main_exp), function(x) lapply(mods, '[[', x)),c('baseline',main_exp))
          models[[i]][[j]] <- lapply(models[[i]][[j]], as.mira)
      }}}
  return(models)
}
models <- fitmodels(modeqs)
rm(fitmodels)
```

# Produce tables

```{r produce-tables, warning = FALSE}
tblit <- function(){
  tables <- alist
  for(i in c('cc','cc_w','imp','imp_w')){
    for(j in outcomes){
      tables[[i]][[j]]$baseline <- tbl_regression(models[[i]][[j]]$baseline, exponentiate = T) %>% bold_labels() %>% italicize_levels()
      for(k in main_exp){
        tables[[i]][[j]][[k]] <- tbl_regression(models[[i]][[j]][[k]], exponentiate = T, include = k) %>% bold_labels() %>% italicize_levels()
        }}}
  return(tables)
  }
tables <- tblit()
rm(tblit)
```

# Group tables

```{r group-tables}
tblcomb <- function(){
  l <- setNames(vector(mode='list', length=length(c('baseline',main_exp))),c('baseline',main_exp))
  outtabs <- list(cc = l, cc_w = l, imp = l, imp_w = l)
  for(i in c('cc','cc_w','imp','imp_w')){
    for(j in c('baseline',main_exp)){
      outtabs[[i]][[j]] <- tbl_merge(list(tables[[i]]$nonuse[[j]],
                                          tables[[i]]$ecig[[j]],
                                          tables[[i]]$exclecig[[j]],
                                          tables[[i]]$dual[[j]]
                                          ), 
                                     tab_spanner = paste0('**',outcomes_labs,'**'))
      }
    outtabs[[i]] <- tbl_stack(outtabs[[i]])
    }
  return(outtabs)
  }
outtabs <- tblcomb()

rm(tblcomb)
```

# Sort data for figures

```{r sort-figdat}
getfigdat <- function(tab){
  out <- data.frame(
  'var' = tab$table_body$variable,
  'var_label' = tab$table_body$var_label,
  'label' = tab$table_body$label,
  'HR' = tab$table_body$estimate,
  'LCI' = tab$table_body$conf.low,
  'UCI' = tab$table_body$conf.high,
  'ref' = tab$table_body$reference_row,
  'header' = tab$table_body$header_row)
  out[,c('HR','LCI','UCI')] <- sapply(out[,c('HR','LCI','UCI')], round, digits = 3)
  out <- out[out$header %in% F,]
  out$fill <- ifelse(out$LCI < 1 & out$UCI > 1, F, T)
  return(out)
}

multgetfigdat <- function(dat){
  out <- do.call('rbind',dat)
  out$var <- factor(out$var, levels=c(baseline_exp, main_exp))
  out$var_label <- factor(out$var_label, levels=tab_labs)
  out$y <- interaction(out$var_label, out$label)
  out$y <- factor(out$y, levels=unique(out$y))
  rownames(out) <- NULL
  return(out)
}

combineit <- function(tables){
  figdat <- alist
  for(i in c('cc','cc_w','imp','imp_w')){
    for(j in outcomes){
      figdat[[i]][[j]] <- multgetfigdat(lapply(tables[[i]][[j]], getfigdat))
    }}
  return(figdat)
}
figdat <- combineit(tables)

longfigdat <- function(df){
  out <- do.call('rbind', df)
  out$outcome <- factor(rep(outcomes,sapply(df[outcomes], nrow)), levels=outcomes, labels=outcomes_labs)
  return(out)
  }
survfigdat <- lapply(figdat, longfigdat)

save(survfigdat, file='C:/Users/qg21962/OneDrive - University of Bristol/Documents/CRUK smoking vaping/Vaping transitions/Outputs/survfigdat.rda')

rm(getfigdat, multgetfigdat, combineit, longfigdat, alist, baseline_exp, main_exp, vaps, tab_labs, outcomes, outcomes_labs)
```

# Tables

## Complete cases

### Unweighted

```{r print-cc-unadj-tab}
outtabs$cc
outtabs$cc |> 
  as_gt() |> 
  gt::gtsave(filename = 'C:/Users/qg21962/OneDrive - University of Bristol/Documents/CRUK smoking vaping/Vaping transitions/Outputs/surv_cc_unadj_tab.docx')
```

### Weighted

```{r print-cc_w-tab}
outtabs$cc_w
outtabs$cc_w |> 
  as_gt() |> 
  gt::gtsave(filename = 'C:/Users/qg21962/OneDrive - University of Bristol/Documents/CRUK smoking vaping/Vaping transitions/Outputs/surv_cc_adj_w_tab.docx')
```

## Imputed

### Unweighted

```{r print-imp-tab}
outtabs$imp
outtabs$imp |> 
  as_gt() |> 
  gt::gtsave(filename = 'C:/Users/qg21962/OneDrive - University of Bristol/Documents/CRUK smoking vaping/Vaping transitions/Outputs/surv_imp_adj_tab.docx')
```

### Weighted

```{r print-imp_w-tab}
outtabs$imp_w
outtabs$imp_w |> 
  as_gt() |> 
  gt::gtsave(filename = 'C:/Users/qg21962/OneDrive - University of Bristol/Documents/CRUK smoking vaping/Vaping transitions/Outputs/surv_imp_adj_w_tab.docx')
```
