---
title: "Correlation and predictor matrices - transitions from smoking to e-cigarette use/non-use in ALSPAC"
author: "Alexandria Andrayas"
date: "21/02/2024"
output: 
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

# Load packages

```{r load-packages}
library(haven)
library(labelled)
library(gtsummary)
library(mice)
library(ggmice)
library(ggplot2)
```

# Load selection data and define labels

```{r selection-data-labs, message=FALSE}
#data
vapdf <- read_dta('//rdsfcifs.acrc.bris.ac.uk/MRC-IEU-research/projects/ieu2/p7/025/working/data/vaping_categories.dta')
expdf <- read_dta('//rdsfcifs.acrc.bris.ac.uk/MRC-IEU-research/projects/ieu2/p7/025/working/data/vaping_exp_measures.dta')

alldf <- merge(vapdf, expdf, by=c('aln','qlet'))
alldf <- to_factor(alldf, sort_levels='auto')
alldf$id <- paste0(alldf$aln, alldf$qlet)
rm(vapdf, expdf)

# 3290 participants answered questions on smoking at 21 yrs (YPA) and not withdrawn consent
alldf <- alldf[!is.na(alldf$smk_21),]

#13 main exposures
selection_exp_labs <- c('sex', 'ethnicity', 'hhincome_11', 'parent_dailsmk_12', 'parent_mh_12',
                        'friends_smk_16', 'eduasp_16', 'alc_16', 'cana_16', 'drug_16', 'exerc_18',
                        'bmi_18_gr', 'mfq_18_gr')

#22 auxiliary variables (maybe add in measures collected after 21 years too?)
selection_aux_labs <- c('hhincome_8', 'hhincome_18', 
                        'parent_dailsmk_2', 'parent_currsmk_18',
                        'parent_mh_1', 'parent_mhmeds_18', 
                        'friends_smk_14', 'friends_smk_18',
                        'eduasp_14', 'qual_18', 
                        'everalc_14', 'alc_18',
                        'evercana_14', 'cana_18',
                        'everdrug_14', 'drug_18',
                        'exerc_16', 'exerc_22',
                        'bmi_16_gr', 'bmi_24_gr',
                        'mfq_14_gr', 'mfq_21_gr')

df <- data.frame(alldf[,c('smk_21',selection_exp_labs,selection_aux_labs)])
head(df)
nrow(df)
```

# Selection correlation matrix

```{r selection-corr-matrix, out.width = '100%'}
sel_corr <- plot_corr(df, rotate = T) +
  theme(axis.text.x = element_text(size=10, hjust=0), 
        axis.text.y = element_text(size=10),
        text=element_text(size=20, family = 'Times New Roman')) +
  labs(tag = 'A')

ggsave(sel_corr, width=8,   height=8, filename = 'C:/Users/qg21962/OneDrive - University of Bristol/Documents/CRUK smoking vaping/Vaping transitions/Outputs/selection_corr_mat_plt.png')
```

# Selection predictor matrix

```{r selection-pred-matrix, message=FALSE}
getmethod <- function(df){
  out <- rep('', ncol(df))
  names(out) <- colnames(df)
  for(i in colnames(df)){
    if(is.numeric(df[,i]) == T){
      out[i] <- ifelse(shapiro.test(df[,i])$p.value < 0.01, 'pmm', 'norm')
    } else if(is.factor(df[,i]) == T & is.ordered(df[,i]) == F){
      out[i] <- ifelse(length(levels(df[,i])) > 2, 'polyreg', 'logreg')
    } else if(is.factor(df[,i]) == T & is.ordered(df[,i]) == T){
      out[i] <- ifelse(length(levels(df[,i])) > 2, 'polr', NA)
    }
  }
  return(out)
}
fcs_method <- getmethod(df)
fcs_method[c('smk_21','sex')] <- ''

predm <- quickpred(df)

predm[c('smk_21','sex'),] <- 0
predm[selection_exp_labs[!selection_exp_labs %in% 'sex'], c('smk_21',selection_exp_labs)] <- 1
diag(predm) <- 0

sel_pred <- plot_pred(predm, rotate = T, label = F, method = fcs_method) +
  theme(axis.text.x = element_text(size=10, hjust=0), 
        axis.text.y = element_text(size=10),
        text=element_text(size=20, family = 'Times New Roman')) +
  labs(tag = 'A')

ggsave(sel_pred, width=8,   height=8, filename = 'C:/Users/qg21962/OneDrive - University of Bristol/Documents/CRUK smoking vaping/Vaping transitions/Outputs/selection_pred_mat_plt.png')
```

# Load analytic data and define exposures

```{r analytic-data-labs, message=FALSE}
subdf <- read_dta('//rdsfcifs.acrc.bris.ac.uk/MRC-IEU-research/projects/ieu2/p7/025/working/data/vaping_sub_measures.dta')
subdf <- to_factor(subdf, sort_levels='auto')

# 5 outcome timepoints
vaps <- c('vap22','vap23','vap24','vap28','vap30')

# 4 baseline exposures
baseline_exp <- c('sex', 'ethnicity', 'hhincome_11', 'parent_dailsmk_12')
  
# 11 main exposures
outcome_exp_labs <- c('bmi_18_gr', 'exerc_18', 'qual_20', 'bingalc_20', 'cana_20', 'drug_20',
                      'friends_smk_20', 'mfq_21_gr', 'townsend_21_gr', 'parent_21', 'freqsmk_21')

# 24 auxiliary variables
outcome_aux_labs <- c('hhincome_8', 'hhincome_18', 
                      'parent_dailsmk_2', 'parent_currsmk_18', 
                      'bmi_16_gr', 'bmi_24_gr',
                      'exerc_16', 'exerc_22',
                      'eduasp_16', 'qual_18', 
                      'alc_16', 'bingalc_18',
                      'cana_16', 'cana_18',
                      'drug_16', 'drug_18',
                      'friends_smk_16', 'friends_smk_18', 
                      'mfq_14_gr', 'mfq_18_gr', 
                      'townsend_18_gr', 'townsend_20_gr',
                      'parent_20','parent_22')

df <- data.frame(subdf[,c(vaps,baseline_exp,outcome_exp_labs,outcome_aux_labs)])
df_w <- cbind(df, 'weights' = subdf$weights)
head(df_w)
nrow(df_w)
```

# Correlations between variables

```{r analytic-corr-matrix, out.width = '100%'}
ana_corr <- plot_corr(df_w, rotate = T) +
  theme(axis.text.x = element_text(size=7, hjust=0), 
        axis.text.y = element_text(size=7),
        text=element_text(size=20, family = 'Times New Roman')) +
  labs(tag = 'B')

ggsave(ana_corr, width=8,   height=8, filename = 'C:/Users/qg21962/OneDrive - University of Bristol/Documents/CRUK smoking vaping/Vaping transitions/Outputs/analytic_corr_mat_plt.png')
```

# Predictor matrix

```{r analytic-pred-matrix, out.width = '100%'}
derivlabs <- c('timeto','firstevent','dual','exclecig','nonuse')
df_w[,derivlabs] <- NA

method <- getmethod(df_w)
method[c('sex','weights')] <- ''

predm <- quickpred(df_w)
predm[c(derivlabs,vaps,baseline_exp,outcome_exp_labs)[!c(derivlabs,vaps,baseline_exp,outcome_exp_labs) %in% 'sex'], c(derivlabs,vaps,baseline_exp,outcome_exp_labs)] <- 1
predm[,'weights'] <- 1
predm[c('sex','weights',derivlabs),] <- 0
predm[vaps,c(derivlabs)] <- 0
predm[,'firstevent'] <- 0
diag(predm) <- 0

ana_pred <- plot_pred(predm, rotate = T, label = F, method = method) +
  theme(axis.text.x = element_text(size=7, hjust=0), 
        axis.text.y = element_text(size=7),
        text=element_text(size=20, family = 'Times New Roman')) +
  labs(tag = 'B')

ggsave(ana_pred, width=8,   height=8, filename = 'C:/Users/qg21962/OneDrive - University of Bristol/Documents/CRUK smoking vaping/Vaping transitions/Outputs/analytic_pred_mat_plt.png')
```
