---
title: "Publication plots - transitions from smoking to e-cigarette use/Neither use in ALSPAC"
author: "Alexandria Andrayas"
date: "29/01/2024"
output: 
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
editor_options: 
  chunk_output_type: console
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

# Load packages and get data

```{r load-packages}
library(ggplot2)
library(ggtext)
library(haven)
library(labelled)
library(sticky)
library(dplyr)
library(tidyr)
library(gtsummary)
library(ggpubr)
library(extrafont)
library(mice)
#library(tidycmprsk)
#library(ggsurvfit)
#font_import()
#loadfonts(device="win")
```

# Get data and specify labels

```{r data-labs}
# set up data
subdf <- read_dta('//rdsfcifs.acrc.bris.ac.uk/MRC-IEU-research/projects/ieu2/p7/025/working/data/vaping_sub_measures.dta')
subdf <- to_factor(subdf, sort_levels='auto')
subdf <- data.frame(subdf)
subdf <- sticky_all(subdf)
subdf$id <- 1:nrow(subdf)

# 4 baseline exposures
confounders <- c('sex', 'ethnicity', 'hhincome_11', 'parent_dailsmk_12')

# 11 main exposures
main_exp <- c('bmi_18_gr', 'exerc_18', 'qual_20', 'bingalc_20', 'cana_20', 'drug_20', 'friends_smk_20', 'freqsmk_21', 'mfq_21_gr', 'townsend_21_gr', 'parent_21')

# 5 timepoints
vaps <- c('vap22', 'vap23', 'vap24', 'vap28', 'vap30')

# imputed data
load('//rdsfcifs.acrc.bris.ac.uk/MRC-IEU-research/projects/ieu2/p7/025/working/data/vaping_impdfs.rda')
impdfs <- lapply(impdfs, function(x){
  x[,'id'] <- 1:nrow(x)
  return(x)
})

load('//rdsfcifs.acrc.bris.ac.uk/MRC-IEU-research/projects/ieu2/p7/025/working/data/vaping_imp.rda')
long_impdf <- complete(imp, 'long')
#convert firstevent to factor
long_impdf$firstevent <- factor(long_impdf$firstevent, levels=c(1:4), labels=c('No event','Dual use','Exclusive e-cigarette use','Neither use'))

round(prop.table(table(long_impdf$firstevent)),2)
round(prop.table(table(subdf$firstevent)),2)
```

# Descriptive stats tables

```{r desc-stats}
desc_tab <- tbl_summary(subdf[, c(confounders, main_exp)], statistic = all_continuous() ~ "{mean} ({sd})", type = all_dichotomous() ~ "categorical", missing = 'no') %>%
  bold_labels() %>%
  italicize_levels() %>%
  add_n(statistic = "{n_miss} ({p_miss}%)") %>%
  modify_header(n = "**Missing**")

desc_tab |> 
  as_gt() |> 
  gt::gtsave(filename = 'C:/Users/qg21962/OneDrive - University of Bristol/Documents/CRUK smoking vaping/Vaping transitions/Outputs/descstats_tab.docx')

desc_tabs_byoutcomes <- tbl_merge(tbls = list(
  tbl_summary(subdf[, c(confounders, main_exp, 'nonuse')], by=nonuse, statistic=all_continuous() ~ "{mean} ({sd})", type = all_dichotomous() ~ "categorical", missing = 'no') %>% add_p(),
  tbl_summary(subdf[, c(confounders, main_exp, 'exclecig')], by=exclecig, statistic=all_continuous() ~ "{mean} ({sd})", type = all_dichotomous() ~ "categorical", missing = 'no') %>% add_p(),
  tbl_summary(subdf[, c(confounders, main_exp, 'dual')], by=dual, statistic=all_continuous() ~ "{mean} ({sd})", type = all_dichotomous() ~ "categorical", missing = 'no') %>% add_p(),
  tbl_summary(subdf[, c(confounders, main_exp, 'ecig')], by=ecig, statistic=all_continuous() ~ "{mean} ({sd})", type = all_dichotomous() ~ "categorical", missing = 'no') %>% add_p(),
  tbl_summary(subdf[!is.na(subdf$firstevent), c(confounders, main_exp)], statistic=all_continuous() ~ "{mean} ({sd})", type = all_dichotomous() ~ "categorical", missing = 'no')
  ), tab_spanner = c('**Neither use**','**Exclusive e-cig use**','**Dual use**','**Any e-cig use**','**Overall**')) %>%
  bold_labels() %>%
  italicize_levels()

desc_tabs_byoutcomes |> 
  as_gt() |> 
  gt::gtsave(filename = 'C:/Users/qg21962/OneDrive - University of Bristol/Documents/CRUK smoking vaping/Vaping transitions/Outputs/descstats_byoutcomes_tab.docx')

#check differences in main exposures by early-life confounders
desc_tabs_byconfounders <- tbl_merge(tbls = list(
  tbl_summary(subdf[, c(confounders, main_exp)], by=sex, statistic=all_continuous() ~ "{mean} ({sd})", type = all_dichotomous() ~ "categorical", missing = 'no') %>% add_p(),
  tbl_summary(subdf[, c(confounders, main_exp)], by=ethnicity, statistic=all_continuous() ~ "{mean} ({sd})", type = all_dichotomous() ~ "categorical", missing = 'no') %>% add_p(),
  tbl_summary(subdf[, c(confounders, main_exp)], by=hhincome_11, statistic=all_continuous() ~ "{mean} ({sd})", type = all_dichotomous() ~ "categorical", missing = 'no') %>% add_p(),
  tbl_summary(subdf[, c(confounders, main_exp)], by=parent_dailsmk_12, statistic=all_continuous() ~ "{mean} ({sd})", type = all_dichotomous() ~ "categorical", missing = 'no') %>% add_p()
  ), tab_spanner = c('**Sex assigned at birth**','**Ethnicity**','**Household income (11y)**','**Parental smoking (12y)**')) %>%
  bold_labels() %>%
  italicize_levels()

desc_tabs_byconfounders |> 
  as_gt() |> 
  gt::gtsave(filename = 'C:/Users/qg21962/OneDrive - University of Bristol/Documents/CRUK smoking vaping/Vaping transitions/Outputs/descstats_byconfounders_tab.docx')

```

# Box plots showing nicotine use categories and missingness per timepoint

```{r box-plts}
p <- list()

#ns categories by timepoint (complete cases)
ns <- data.frame(n = as.vector(sapply(subdf[,vaps], table, useNA = "ifany")), 
                 cat = rep(c('Exclusive smoking','Dual use','Exclusive e-cig use','Neither use','Missing'), 5),
                 time = rep(c(22,23,24,28,30), each=5))

ns$cat <- factor(ns$cat, levels=c('Exclusive smoking','Dual use','Exclusive e-cig use','Neither use','Missing'))

p$ncat <- ggplot(ns, aes(x = time, y = n, fill = cat)) +
  geom_bar(stat="identity", position = 'dodge', colour = 'black') +
  labs(x = '\nTimepoint', y = 'N\n', fill = '') +
  theme_bw() +
  theme(plot.title = element_text(face="bold", hjust=0.5), 
        legend.position = 'bottom', 
        legend.spacing.x = unit(5, 'cm'), 
        text=element_text(size=20, family = 'Times New Roman')) +
  scale_x_continuous(breaks=seq(22,30,1)) +
  scale_y_continuous(limits=c(0,450), breaks=seq(0,450,50)) +
  scale_fill_manual(values=c("grey30", "grey50", "grey70", "grey90", "white")) +
  guides(fill = guide_legend(byrow = TRUE), colour = 'none')

ggsave(p$ncat, width=12,   height=10, filename = 'C:/Users/qg21962/OneDrive - University of Bristol/Documents/CRUK smoking vaping/Vaping transitions/Outputs/ns_percat_plt.png')
```

# Cumulative incidence plots

```{r cuminc-plts}
fit <- survival::survfit(survival::Surv(timeto, firstevent) ~ 1, data = long_impdf)
psta <- as.data.frame(fit$pstate)
colnames(psta) <- fit$states
psta$times <- fit$time
event <- value <- strata <- NULL
pstal <- gather(psta, event, value, -times)
pstal$event[pstal$event %in% '(s0)'] <- 'No event'
pstal <- rbind(pstal,
               data.frame(times=rep(0,4),
                          event=c('No event','Neither use','Exclusive e-cigarette use','Dual use'),
                          value=c(1,0,0,0)))

p$cuminc_imp <- ggplot(pstal, aes(times, value, fill=event)) +
  geom_area() + 
  scale_x_continuous(limits=c(0,9), breaks=c(0,1,2,3,7,9)) +
  theme_bw() +
  theme(text=element_text(size = 20, family = 'Times New Roman'), 
        legend.position = 'bottom', legend.box='vertical', 
        legend.key=element_rect(colour="black")) +
  labs(x = '\nApproximate years from 21+ questionnaire', y = 'Probability\n', fill = NULL) +
  scale_fill_manual(values=c('No event'='grey100', 'Dual use'='grey20', 'Exclusive e-cigarette use'='grey50','Neither use'='grey80'))

ggsave(p$cuminc_imp, width=12, height=10, filename = 'C:/Users/qg21962/OneDrive - University of Bristol/Documents/CRUK smoking vaping/Vaping transitions/Outputs/cuminc_stacked_imp_plt.png')
```

# Plots with subdistribution hazard results

```{r produce-surv-plots}
load('C:/Users/qg21962/OneDrive - University of Bristol/Documents/CRUK smoking vaping/Vaping transitions/Outputs/subdistfigdat_adj.rda')

levels(subdistfigdat$imp_w$outcome)[levels(subdistfigdat$imp_w$outcome) %in% 'E-cigarette use'] <- 'Any e-cigarette use'
levels(subdistfigdat$imp_w$outcome)[levels(subdistfigdat$imp_w$outcome) %in% 'Exclusive e-cig use'] <- 'Exclusive e-cigarette use'
levels(subdistfigdat$imp_w$outcome)[levels(subdistfigdat$imp_w$outcome) %in% 'Non-use'] <- 'Neither use'

subdistfigdat$imp_w <- subdistfigdat$imp_w[!(subdistfigdat$imp_w$outcome %in% 'Neither use' & subdistfigdat$imp_w$ecig_collapsed %in% T),]

subdistfigdat$imp_w$var_label <- recode(subdistfigdat$imp_w$var_label, 
  "Frequency of exercise, past year (18y)" = "Exercise (18y)",
  "Educational qualifications (20y)" = "Education (20y)",
  "Mood and Feelings Questionnaire scores (21y)" = "Mental health (21y)",
  "Binge drinking, six or more units (20y)" = "Binge drinking (20y)",
  "G1 Townsend deprivation score, quintiles (21y)" = "Neighbourhood deprivation (21y)",
  "Is a parent (21y)" = "Parenthood (21y)"
  )

subdistfigdat$imp_w$var_label <- factor(subdistfigdat$imp_w$var_label, levels=c('Sex assigned at birth', 'Ethnicity', 'Household income (11y)', 'Parental smoking (12y)', 'BMI (18y)', 'Exercise (18y)', 'Education (20y)', 'Binge drinking (20y)','Cannabis use (20y)', 'Drug use (20y)','Peer smoking (20y)','Smoking frequency (21y)','Mental health (21y)','Neighbourhood deprivation (21y)','Parenthood (21y)'))

subdistfigdat$imp_w$y <- interaction(subdistfigdat$imp_w$var_label, subdistfigdat$imp_w$label)
subdistfigdat$imp_w$y <- factor(subdistfigdat$imp_w$y, levels=unique(subdistfigdat$imp_w$y))

pltit <- function(df){
  df <- df[!df$var %in% c('sex','ethnicity','hhincome_11','parent_dailsmk_12'),]
  df <- df[!df$ref %in% T,]
  pd <- position_dodge(0.8)
  p <- ggplot(df, aes(x=HR, xmin=LCI, xmax=UCI, y=y), colour='black') +
    geom_vline(xintercept = 1, color = "grey40", linetype = "dashed") +
    geom_errorbar(width=.2, position = pd) +
    geom_point(size=4, position = pd) +
    facet_grid(var_label ~ outcome, scales = "free_y", switch = 'y') +
    scale_x_log10() + 
    scale_y_discrete(labels=setNames(df$label, df$y), position = "right") +
    scale_linetype_manual(values=1) +
    scale_shape_manual(values=21) +
    scale_fill_identity() +
    theme_bw() +
    theme(text=element_text(size=30, family = 'Times New Roman'), 
          strip.background = element_blank(), 
          strip.placement = "outside", 
          strip.text.x = element_text(face = 'bold'),
          strip.text.y.left = element_text(angle = 0, hjust = 1, face = 'bold'),
          axis.text.y=element_blank()) +
    labs(x = "\nSub-distribution hazard ratio (SHR)\n", y = '') + 
    guides(linetype = guide_legend(nrow = 1), 
           shape = guide_legend(nrow = 1, override.aes = list(size = 3, fill = 'black')))
  return(p)
}
subdistplts <- lapply(subdistfigdat, pltit)

ggsave(subdistplts$imp_w, width=26,   height=15, filename = 'C:/Users/qg21962/OneDrive - University of Bristol/Documents/CRUK smoking vaping/Vaping transitions/Outputs/subdist_imp_w_plt_nolabs.png')
```

# Get p-values

```{r produce-surv-plots}
#pvals
##calculate the standard error
SE = (u − l)/(2×1.96)

##calculate the test statistic
z = Est/SE

##
P = exp(−0.717×z − 0.416×z2)

e.g. for freqsmk_21 any e-cig

(4.530 - 2.180)/(2*1.96)
3.143/0.5994898
```
